title: "projets.pl"
url: "https://projets.pl" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""
lang: "pl"

markdown: kramdown

sass:
  sass_dir: assets
  style: compressed

toc:
  min_level: 2
  max_level: 3

plugins:
  - jekyll-sitemap
  - jekyll-toc

collections_dir: 
collections:
  posts:    
    output: true
    permalink: /blog/:title:output_ext
  services:    
    output: true
    permalink: /uslugi/:title:output_ext
  casestudies:    
    output: false
    # permalink: /realizacje/:title:output_ext
  technologies:    
    output: false
    # permalink: /technologie/:title:output_ext


defaults:  
  -
    scope:
      path: "pages"
    values:
      permalink: /:basename:output_ext