markdown: kramdown

sass:
  sass_dir: assets/_scss
  style: compressed

toc:
  min_level: 2
  max_level: 3

plugins:
  - jekyll-sitemap
  - jekyll-toc

collections_dir: 
collections:
  posts:    
    output: true
    permalink: /blog/:title:output_ext
  services:    
    output: true
    permalink: /uslugi/:title:output_ext
  casestudies:    
    output: true
    permalink: /realizacje/:title:output_ext
  technologies:    
    output: true
    permalink: /technologie/:title:output_ext


defaults:  
  -
    scope:
      path: "pages"
    values:
      permalink: /:basename:output_ext